/*----- PROTECTED REGION ID(JaiGenicamDSStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        JaiGenicamDSStateMachine.cpp
//
// description : State machine file for the JaiGenicamDS class
//
// project :     JaiGenicamDS
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <JaiGenicamDS.h>

/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::JaiGenicamDSStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  Connected to camera, not acquiring images
//  UNKNOWN  |  Not connected to camera. Connection problems.
//  FAULT    |  Connected to camera, camera fault detected
//  RUNNING  |  Connected to camera, acquiring images
//  OFF      |  Disconnected from camera


namespace JaiGenicamDS_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ExposureTime_allowed()
 *	Description : Execution allowed for ExposureTime attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ExposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExposureTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExposureTimeStateAllowed_WRITE

	//	Not any excluded states for ExposureTime attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExposureTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExposureTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::GainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_FrameRate_allowed()
 *	Description : Execution allowed for FrameRate attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_FrameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for FrameRate attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::FrameRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::FrameRateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_TriggerSource_allowed()
 *	Description : Execution allowed for TriggerSource attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_TriggerSource_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TriggerSource attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::TriggerSourceStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::TriggerSourceStateAllowed_WRITE

	//	Not any excluded states for TriggerSource attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::TriggerSourceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::TriggerSourceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_FrameCounter_allowed()
 *	Description : Execution allowed for FrameCounter attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_FrameCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::FrameCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::FrameCounterStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_TriggerMode_allowed()
 *	Description : Execution allowed for TriggerMode attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_TriggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for TriggerMode attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::TriggerModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::TriggerModeStateAllowed_WRITE

	//	Not any excluded states for TriggerMode attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::TriggerModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::TriggerModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ImageHeight_allowed()
 *	Description : Execution allowed for ImageHeight attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ImageHeight_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::ImageHeightStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageHeightStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Not any excluded states for ImageHeight attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ImageHeightStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageHeightStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ImageWidth_allowed()
 *	Description : Execution allowed for ImageWidth attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ImageWidth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::ImageWidthStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageWidthStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Not any excluded states for ImageWidth attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ImageWidthStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageWidthStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ImageOffsetX_allowed()
 *	Description : Execution allowed for ImageOffsetX attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ImageOffsetX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::ImageOffsetXStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageOffsetXStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Not any excluded states for ImageOffsetX attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ImageOffsetXStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageOffsetXStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ImageOffsetY_allowed()
 *	Description : Execution allowed for ImageOffsetY attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ImageOffsetY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::ImageOffsetYStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageOffsetYStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Not any excluded states for ImageOffsetY attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ImageOffsetYStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageOffsetYStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_PixelFormat_allowed()
 *	Description : Execution allowed for PixelFormat attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_PixelFormat_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::RUNNING)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::PixelFormatStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::PixelFormatStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Not any excluded states for PixelFormat attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::PixelFormatStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::PixelFormatStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Image_allowed()
 *	Description : Execution allowed for Image attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Image_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(JaiGenicamDS::ImageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_start_allowed()
 *	Description : Execution allowed for start attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(JaiGenicamDS::startStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::startStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_stop_allowed()
 *	Description : Execution allowed for stop attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(JaiGenicamDS::stopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::stopStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(JaiGenicamDS::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(JaiGenicamDS::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_GetCameraList_allowed()
 *	Description : Execution allowed for GetCameraList attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_GetCameraList_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetCameraList command.
	/*----- PROTECTED REGION ID(JaiGenicamDS::GetCameraListStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::GetCameraListStateAllowed
	return true;
}

}	//	End of namespace
