/*----- PROTECTED REGION ID(JaiGenicamDSStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        JaiGenicamDSStateMachine.cpp
//
// description : State machine file for the JaiGenicamDS class
//
// project :     JaiGenicamDS
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <JaiGenicamDS.h>

/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::JaiGenicamDSStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  Connected to camera, not acquiring images
//  UNKNOWN  |  Not connected to camera. Connection problems.
//  FAULT    |  Connected to camera, camera fault detected
//  RUNNING  |  Connected to camera, acquiring images
//  OFF      |  Disconnected from camera


namespace JaiGenicamDS_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ExposureTime_allowed()
 *	Description : Execution allowed for ExposureTime attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ExposureTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureTime attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExposureTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExposureTimeStateAllowed_WRITE

	//	Not any excluded states for ExposureTime attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExposureTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExposureTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::GainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_FrameRate_allowed()
 *	Description : Execution allowed for FrameRate attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_FrameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FrameRate attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::FrameRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::FrameRateStateAllowed_WRITE

	//	Not any excluded states for FrameRate attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::FrameRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::FrameRateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_ExternalTrigger_allowed()
 *	Description : Execution allowed for ExternalTrigger attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_ExternalTrigger_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExternalTrigger attribute in Write access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExternalTriggerStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExternalTriggerStateAllowed_WRITE

	//	Not any excluded states for ExternalTrigger attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ExternalTriggerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ExternalTriggerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_FrameCounter_allowed()
 *	Description : Execution allowed for FrameCounter attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_FrameCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for FrameCounter attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::FrameCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::FrameCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Image_allowed()
 *	Description : Execution allowed for Image attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Image_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Image attribute in read access.
	/*----- PROTECTED REGION ID(JaiGenicamDS::ImageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::ImageStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_start_allowed()
 *	Description : Execution allowed for start attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(JaiGenicamDS::startStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::startStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_stop_allowed()
 *	Description : Execution allowed for stop attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(JaiGenicamDS::stopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::stopStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(JaiGenicamDS::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : JaiGenicamDS::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool JaiGenicamDS::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(JaiGenicamDS::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	JaiGenicamDS::OnStateAllowed
	return true;
}

}	//	End of namespace
